# Generated by Django 4.2.4 on 2023-08-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_cod_register_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cod_register',
            field=models.CharField(blank=True, max_length=6, verbose_name='Registration code'),
        ),
    ]
